### ISSUE TITLE
Linearization view title should also contain the currently selected entity name

### ISSUE THREAD

**Issue by soimugeoWB** [who-icatx/webprotege-linearization-service#32]
Linearization view title should also contain the currently selected entity name
![Image](https://github.com/user-attachments/assets/0fd72375-0590-47cd-bfb2-a5825dc22f9e)

**Comment by alexsilaghi** [comment]
https://github.com/protegeproject/webprotege-gwt-ui/pull/90 this is the merge request that fixes the issue.
